name: Java Build
permissions:
  pull-requests: write

on:
  push:
    branches: ["main"]

  pull_request:
    branches: ["main", "release-*"]

  schedule:
    # daily at 1:30 UTC
    - cron:  '30 1 * * *'
    
concurrency:
  group: java-build-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-20.04 ]
        java: [ "11", "17" ]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@5ffc13f4174014e2d4d4572b3d74c3fa61aeb2c2
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          cache: 'maven'
      - name: Build JAR Artifacts
        run: mvn --batch-mode --errors --update-snapshots clean package -Drevision=$(git describe --tags --always)
      - name: Add coverage to PR
        # avoid duplicate coverage reports
        if: matrix.java == 11
        uses: madrapps/jacoco-report@7ce0d588f6d00dd4a7b63a597383332e0c5c72d0
        with:
          paths: ${{ github.workspace }}/target/site/jacoco/jacoco.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 50
          min-coverage-changed-files: 50